name: GitHub Actions Demo
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - run: bundle exec rake
    strategy:
      matrix:
        ruby: ['2.6.9', '2.7.3', '3.1.1', '3.0.3']
