name: CI
on:
  workflow_dispatch:
  push:
    branches: [ master switch-cf-gem ]
  pull_request:
    branches: [ master switch-cf-gem ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - run: bundle exec rake
    strategy:
      matrix:
        ruby: ['2.6.10', '2.7.6', '3.1.2', '3.0.4']
